##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/wallpcrb/public_html/
    - /bin/cp -R .vscode $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp apply.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp support.html $DEPLOYPATH
    - /bin/cp wallx.css $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH